### PR TITLE
Use AltGr to support the whole ASCII set

### PR DESCRIPTION
**Pull request by edgar-bonet**
This adds supports for the 11 ASCII characters that where missing, as they require holding the AltGr key:

```text
~ # { [ | ` \ ^ @ ] }
```

The information on whether Shift or AltGr is required to produce the key is stored in bits 6 and 7 of `_asciimapFr[character]`. This is possible because all keys that are used with either of those modifiers have those two bits clear. The interpretation of these two bits is:

| bits | meaning      |
|------|--------------|
|  00  | no modifier¹ |
|  01  | no modifier  |
|  10  | Shift        |
|  11  | AltGr        |

¹ only keys in this group are ever used with modifiers.

Note that this pull request is a superset of pull request #4, which is needed to have the `+` key work.

### CODE REVIEW

**Comment by edgar-bonet** [comment]
I wrote:
> all keys that are used with either of [the Sift or AltGr] modifiers have [bits 6 and&nbsp;7] clear.

Oops! Missed key `0x64` (characters `'<'` and `'>'`). I'll go fix that.

**Comment by martin-leo** [comment]
OK, just let me know when it's ready !

**Comment by edgar-bonet** [comment]
I fixed the issue by replacing the problematic key code `0x64` by the unused code `0x32`. I then amended and force-pushed the commit.

**Comment by edgar-bonet** [comment]
Oh, and by the way, this PR is ready for review. :wink:

**Comment by martin-leo** [comment]
Ok, I will have to generate a new release to make this available in the Arduino IDE. Have you planned to do some more merge request in the following days/weeks (I guess I should try to limit the number of releases).

**Comment by edgar-bonet** [comment]
Hi! No, I do not plan to do more merge requests in this repository for the foreseeable future.

**Pull request merged**
