### PR TITLE
Rename KeyReport to KeyReportFr and _asciimap to _asciimapFr

### PR DESCRIPTION
**Pull request by barchstien**
Hi Leo

I want to use both the original keyboard (english us layout) and keyboardAzertyFr in the same arduino sketch. The compilation was failing for minor reason which are fixed by this PR

### CODE REVIEW

**Comment by MedyOsef** [comment]
I do not understand

**Comment by barchstien** [comment]
Hi Medy

I have an arduino sketch. I am using an include on both keyboard and keybaordAzertyFr
`#include <Keyboard.h>
#include <KeyboardAzertyFr.h>`
That is because I want to support both french and english layout.
Which fails to compile, because the same `struct KeyReport` and the same `const uint8_t _asciimap[128]` are defined in Keyboard.h and KeyboardAzertyFr.h
To be more precise _asciimap is only defined in cpp, so it fails when linking, not when compiling, because the same symbol is used twice.
I have fixed that issue by renaming `KeyReport` to `KeyReportFr` and `_asciimap` to `_asciimapFr`

This very pull request does that renaming.
The interface is not changed, meaning those changes are transparent (invisible) to users of the library KeyboardAzertyFr

**Comment by martin-leo** [comment]
Thanks @barchstien.

Now I guess someone (me ?) should integrate [the modifications of the 1.0.2 version of the original library ](https://github.com/arduino-libraries/Keyboard/compare/1.0.1...1.0.2) and release this as the 1.0.2 version of this version. I personnaly do not have the time to do it now, maybe later.

**Comment by barchstien** [comment]
> Thanks @barchstien.
> 
> Now I guess someone (me ?) should integrate [the modifications of the 1.0.2 version of the original library ](https://github.com/arduino-libraries/Keyboard/compare/1.0.1...1.0.2) and release this as the 1.0.2 version of this version. I personnaly do not have the time to do it now, maybe later.

You've seen that one coming ! :-p
https://github.com/martin-leo/KeyboardAzertyFr/pull/2

**Comment by MedyOsef** [comment]
Can you show me your code if it's not intrusive?

**Comment by martin-leo** [comment]
@MedyOsef : not sure to understand your request. All the code is available on the git repository, are you looking for something else ?

**Pull request merged**
